### ISSUE TITLE
 The readme is not consistent with the example readme or other readmes in the organization

### ISSUE THREAD

**Issue by ppjena** [SoftwareEngineeringToolDemos/ICSE-2014-semSMT#9]
This readme of your group SketchLink Can seem to be useful
# FSE-2014-SketchLink

Linking Sketches and Diagrams to Source Code Artifacts

This repository contains information related to the tool SketchLink presented in the Foundations of Software Engineering, 2014. The tool was originally presented in <a href="http://dl.acm.org/citation.cfm?id=2661672&dl=ACM&coll=DL&CFID=717271653&CFTOKEN=32010874">this paper</a>.

This repository is not the original repository for this tool. Here are some links to the original project:

<a href="http://www.uni-trier.de/index.php?id=54142&L=2">The Official Project Page, including video on tool.</a>

In this repository, for ExampleTool you will find:

:x: Source code (not available)

:x: Executable tool (not available)

SketchLink is not available to redistribute or provide the source code. Please contact Sebastian Baltes and Stephen Diehl to receive an executable version of the tool.

This repository was constructed by <a href="https://github.com/satish2">Satish Inampudi</a> under the supervision of <a href="https://github.com/CaptainEmerson">Murphy Emerson-Hill</a>. Thanks to <a href="http://www.uni-trier.de/index.php?id=49237&L=2">Sebastian Baltes</a> for his help in establishing this repository.

**Comment by cskimpel** [comment]
Did not understand what was not inline with the example. 
In this case, the tools is unworkable, so it would not include all of the elements of a tool that is working. Maybe that is what they were referring to.
